name: "Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout self"
      uses: actions/checkout@v4
    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: "Install dependencies"
      working-directory: ./app
      shell: bash
      run: |
        npm ci
    - name: "Build website"
      working-directory: ./app
      shell: bash
      run: |
        npm run build
    # - name: "Copy CNAME to build folder for custom domain"
    #   shell: bash
    #   run: |
    #     cp ./CNAME ./build/CNAME
    - name: "Upload build artifact"
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: ./app/build
  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: "Download build artifact"
      uses: actions/download-artifact@v3
      with:
        name: application
    - name: "Deploy to GitHub Pages"
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com